version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: todai_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todai_backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/todai_db
      JWT_SECRET_KEY: your-secret-key-change-in-production-todai-2025
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: python app.py

volumes:
  postgres_data: